#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cine
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cinex")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCine(Cine instance);
    partial void UpdateCine(Cine instance);
    partial void DeleteCine(Cine instance);
    partial void InsertTipo_Cine(Tipo_Cine instance);
    partial void UpdateTipo_Cine(Tipo_Cine instance);
    partial void DeleteTipo_Cine(Tipo_Cine instance);
    partial void InsertPelicula(Pelicula instance);
    partial void UpdatePelicula(Pelicula instance);
    partial void DeletePelicula(Pelicula instance);
    partial void InsertCensura(Censura instance);
    partial void UpdateCensura(Censura instance);
    partial void DeleteCensura(Censura instance);
    partial void InsertPais(Pais instance);
    partial void UpdatePais(Pais instance);
    partial void DeletePais(Pais instance);
    partial void InsertGenero(Genero instance);
    partial void UpdateGenero(Genero instance);
    partial void DeleteGenero(Genero instance);
    partial void InsertSala(Sala instance);
    partial void UpdateSala(Sala instance);
    partial void DeleteSala(Sala instance);
    partial void InsertTipo_Modalidad(Tipo_Modalidad instance);
    partial void UpdateTipo_Modalidad(Tipo_Modalidad instance);
    partial void DeleteTipo_Modalidad(Tipo_Modalidad instance);
    partial void InsertTipo_Empleado(Tipo_Empleado instance);
    partial void UpdateTipo_Empleado(Tipo_Empleado instance);
    partial void DeleteTipo_Empleado(Tipo_Empleado instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertFuncion(Funcion instance);
    partial void UpdateFuncion(Funcion instance);
    partial void DeleteFuncion(Funcion instance);
    partial void InsertTipo_Entrada(Tipo_Entrada instance);
    partial void UpdateTipo_Entrada(Tipo_Entrada instance);
    partial void DeleteTipo_Entrada(Tipo_Entrada instance);
    partial void InsertButaca(Butaca instance);
    partial void UpdateButaca(Butaca instance);
    partial void DeleteButaca(Butaca instance);
    partial void InsertFuncion_Entrada(Funcion_Entrada instance);
    partial void UpdateFuncion_Entrada(Funcion_Entrada instance);
    partial void DeleteFuncion_Entrada(Funcion_Entrada instance);
    partial void InsertReserva(Reserva instance);
    partial void UpdateReserva(Reserva instance);
    partial void DeleteReserva(Reserva instance);
    partial void InsertDetalle_Reserva(Detalle_Reserva instance);
    partial void UpdateDetalle_Reserva(Detalle_Reserva instance);
    partial void DeleteDetalle_Reserva(Detalle_Reserva instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Proyecto_Cine.Properties.Settings.Default.CinexConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Cine> Cines
		{
			get
			{
				return this.GetTable<Cine>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Cine> Tipo_Cines
		{
			get
			{
				return this.GetTable<Tipo_Cine>();
			}
		}
		
		public System.Data.Linq.Table<Pelicula> Peliculas
		{
			get
			{
				return this.GetTable<Pelicula>();
			}
		}
		
		public System.Data.Linq.Table<Censura> Censuras
		{
			get
			{
				return this.GetTable<Censura>();
			}
		}
		
		public System.Data.Linq.Table<Pais> Pais
		{
			get
			{
				return this.GetTable<Pais>();
			}
		}
		
		public System.Data.Linq.Table<Genero> Generos
		{
			get
			{
				return this.GetTable<Genero>();
			}
		}
		
		public System.Data.Linq.Table<Sala> Salas
		{
			get
			{
				return this.GetTable<Sala>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Modalidad> Tipo_Modalidads
		{
			get
			{
				return this.GetTable<Tipo_Modalidad>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Empleado> Tipo_Empleados
		{
			get
			{
				return this.GetTable<Tipo_Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleados
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Funcion> Funcions
		{
			get
			{
				return this.GetTable<Funcion>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Entrada> Tipo_Entradas
		{
			get
			{
				return this.GetTable<Tipo_Entrada>();
			}
		}
		
		public System.Data.Linq.Table<Butaca> Butacas
		{
			get
			{
				return this.GetTable<Butaca>();
			}
		}
		
		public System.Data.Linq.Table<Funcion_Entrada> Funcion_Entradas
		{
			get
			{
				return this.GetTable<Funcion_Entrada>();
			}
		}
		
		public System.Data.Linq.Table<Reserva> Reservas
		{
			get
			{
				return this.GetTable<Reserva>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Reserva> Detalle_Reservas
		{
			get
			{
				return this.GetTable<Detalle_Reserva>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCLIENTE;
		
		private string _DNI;
		
		private string _NOMBRE;
		
		private string _APELLIDO;
		
		private string _CORREO;
		
		private string _FECHADENACIMIENTO;
		
		private System.Nullable<bool> _Habilitado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCLIENTEChanging(int value);
    partial void OnIDCLIENTEChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnCORREOChanging(string value);
    partial void OnCORREOChanged();
    partial void OnFECHADENACIMIENTOChanging(string value);
    partial void OnFECHADENACIMIENTOChanged();
    partial void OnHabilitadoChanging(System.Nullable<bool> value);
    partial void OnHabilitadoChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this.OnIDCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDCLIENTE = value;
					this.SendPropertyChanged("IDCLIENTE");
					this.OnIDCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this.OnAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO = value;
					this.SendPropertyChanged("APELLIDO");
					this.OnAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(50)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this.OnCORREOChanging(value);
					this.SendPropertyChanging();
					this._CORREO = value;
					this.SendPropertyChanged("CORREO");
					this.OnCORREOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHADENACIMIENTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FECHADENACIMIENTO
		{
			get
			{
				return this._FECHADENACIMIENTO;
			}
			set
			{
				if ((this._FECHADENACIMIENTO != value))
				{
					this.OnFECHADENACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._FECHADENACIMIENTO = value;
					this.SendPropertyChanged("FECHADENACIMIENTO");
					this.OnFECHADENACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habilitado", DbType="Bit")]
		public System.Nullable<bool> Habilitado
		{
			get
			{
				return this._Habilitado;
			}
			set
			{
				if ((this._Habilitado != value))
				{
					this.OnHabilitadoChanging(value);
					this.SendPropertyChanging();
					this._Habilitado = value;
					this.SendPropertyChanged("Habilitado");
					this.OnHabilitadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cine")]
	public partial class Cine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCINE;
		
		private string _NOMBRE;
		
		private int _IDTIPOCINE;
		
		private string _DIRECCION;
		
		private string _FECHA_APERTURA;
		
		private bool _HABILITADO;
		
		private string _CONTACTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCINEChanging(int value);
    partial void OnIDCINEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnIDTIPOCINEChanging(int value);
    partial void OnIDTIPOCINEChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnFECHA_APERTURAChanging(string value);
    partial void OnFECHA_APERTURAChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    partial void OnCONTACTOChanging(string value);
    partial void OnCONTACTOChanged();
    #endregion
		
		public Cine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCINE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCINE
		{
			get
			{
				return this._IDCINE;
			}
			set
			{
				if ((this._IDCINE != value))
				{
					this.OnIDCINEChanging(value);
					this.SendPropertyChanging();
					this._IDCINE = value;
					this.SendPropertyChanged("IDCINE");
					this.OnIDCINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOCINE", DbType="Int NOT NULL")]
		public int IDTIPOCINE
		{
			get
			{
				return this._IDTIPOCINE;
			}
			set
			{
				if ((this._IDTIPOCINE != value))
				{
					this.OnIDTIPOCINEChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOCINE = value;
					this.SendPropertyChanged("IDTIPOCINE");
					this.OnIDTIPOCINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(50)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_APERTURA", DbType="NVarChar(50)")]
		public string FECHA_APERTURA
		{
			get
			{
				return this._FECHA_APERTURA;
			}
			set
			{
				if ((this._FECHA_APERTURA != value))
				{
					this.OnFECHA_APERTURAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_APERTURA = value;
					this.SendPropertyChanged("FECHA_APERTURA");
					this.OnFECHA_APERTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTO", DbType="NVarChar(50)")]
		public string CONTACTO
		{
			get
			{
				return this._CONTACTO;
			}
			set
			{
				if ((this._CONTACTO != value))
				{
					this.OnCONTACTOChanging(value);
					this.SendPropertyChanging();
					this._CONTACTO = value;
					this.SendPropertyChanged("CONTACTO");
					this.OnCONTACTOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Cine")]
	public partial class Tipo_Cine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPOCINE;
		
		private string _NOMBRE;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPOCINEChanging(int value);
    partial void OnIDTIPOCINEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Tipo_Cine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOCINE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDTIPOCINE
		{
			get
			{
				return this._IDTIPOCINE;
			}
			set
			{
				if ((this._IDTIPOCINE != value))
				{
					this.OnIDTIPOCINEChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOCINE = value;
					this.SendPropertyChanged("IDTIPOCINE");
					this.OnIDTIPOCINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pelicula")]
	public partial class Pelicula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPELICULA;
		
		private string _TITULO;
		
		private string _FECHA_ESTRENO;
		
		private System.Nullable<int> _IDGENERO;
		
		private System.Nullable<int> _IDPAIS;
		
		private string _SINOPSIS;
		
		private string _DURACION;
		
		private int _IDTIPOCENSURA;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPELICULAChanging(int value);
    partial void OnIDPELICULAChanged();
    partial void OnTITULOChanging(string value);
    partial void OnTITULOChanged();
    partial void OnFECHA_ESTRENOChanging(string value);
    partial void OnFECHA_ESTRENOChanged();
    partial void OnIDGENEROChanging(System.Nullable<int> value);
    partial void OnIDGENEROChanged();
    partial void OnIDPAISChanging(System.Nullable<int> value);
    partial void OnIDPAISChanged();
    partial void OnSINOPSISChanging(string value);
    partial void OnSINOPSISChanged();
    partial void OnDURACIONChanging(string value);
    partial void OnDURACIONChanged();
    partial void OnIDTIPOCENSURAChanging(int value);
    partial void OnIDTIPOCENSURAChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Pelicula()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPELICULA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPELICULA
		{
			get
			{
				return this._IDPELICULA;
			}
			set
			{
				if ((this._IDPELICULA != value))
				{
					this.OnIDPELICULAChanging(value);
					this.SendPropertyChanging();
					this._IDPELICULA = value;
					this.SendPropertyChanged("IDPELICULA");
					this.OnIDPELICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this.OnTITULOChanging(value);
					this.SendPropertyChanging();
					this._TITULO = value;
					this.SendPropertyChanged("TITULO");
					this.OnTITULOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ESTRENO", DbType="NVarChar(50)")]
		public string FECHA_ESTRENO
		{
			get
			{
				return this._FECHA_ESTRENO;
			}
			set
			{
				if ((this._FECHA_ESTRENO != value))
				{
					this.OnFECHA_ESTRENOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ESTRENO = value;
					this.SendPropertyChanged("FECHA_ESTRENO");
					this.OnFECHA_ESTRENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGENERO", DbType="Int")]
		public System.Nullable<int> IDGENERO
		{
			get
			{
				return this._IDGENERO;
			}
			set
			{
				if ((this._IDGENERO != value))
				{
					this.OnIDGENEROChanging(value);
					this.SendPropertyChanging();
					this._IDGENERO = value;
					this.SendPropertyChanged("IDGENERO");
					this.OnIDGENEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPAIS", DbType="Int")]
		public System.Nullable<int> IDPAIS
		{
			get
			{
				return this._IDPAIS;
			}
			set
			{
				if ((this._IDPAIS != value))
				{
					this.OnIDPAISChanging(value);
					this.SendPropertyChanging();
					this._IDPAIS = value;
					this.SendPropertyChanged("IDPAIS");
					this.OnIDPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINOPSIS", DbType="NVarChar(MAX)")]
		public string SINOPSIS
		{
			get
			{
				return this._SINOPSIS;
			}
			set
			{
				if ((this._SINOPSIS != value))
				{
					this.OnSINOPSISChanging(value);
					this.SendPropertyChanging();
					this._SINOPSIS = value;
					this.SendPropertyChanged("SINOPSIS");
					this.OnSINOPSISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURACION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DURACION
		{
			get
			{
				return this._DURACION;
			}
			set
			{
				if ((this._DURACION != value))
				{
					this.OnDURACIONChanging(value);
					this.SendPropertyChanging();
					this._DURACION = value;
					this.SendPropertyChanged("DURACION");
					this.OnDURACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOCENSURA", DbType="Int NOT NULL")]
		public int IDTIPOCENSURA
		{
			get
			{
				return this._IDTIPOCENSURA;
			}
			set
			{
				if ((this._IDTIPOCENSURA != value))
				{
					this.OnIDTIPOCENSURAChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOCENSURA = value;
					this.SendPropertyChanged("IDTIPOCENSURA");
					this.OnIDTIPOCENSURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Censura")]
	public partial class Censura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCENSURA;
		
		private string _NOMBRECENSURA;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCENSURAChanging(int value);
    partial void OnIDCENSURAChanged();
    partial void OnNOMBRECENSURAChanging(string value);
    partial void OnNOMBRECENSURAChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Censura()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCENSURA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCENSURA
		{
			get
			{
				return this._IDCENSURA;
			}
			set
			{
				if ((this._IDCENSURA != value))
				{
					this.OnIDCENSURAChanging(value);
					this.SendPropertyChanging();
					this._IDCENSURA = value;
					this.SendPropertyChanged("IDCENSURA");
					this.OnIDCENSURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRECENSURA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRECENSURA
		{
			get
			{
				return this._NOMBRECENSURA;
			}
			set
			{
				if ((this._NOMBRECENSURA != value))
				{
					this.OnNOMBRECENSURAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRECENSURA = value;
					this.SendPropertyChanged("NOMBRECENSURA");
					this.OnNOMBRECENSURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pais")]
	public partial class Pais : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPAIS;
		
		private string _PAIS;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPAISChanging(int value);
    partial void OnIDPAISChanged();
    partial void OnPAISChanging(string value);
    partial void OnPAISChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Pais()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPAIS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPAIS
		{
			get
			{
				return this._IDPAIS;
			}
			set
			{
				if ((this._IDPAIS != value))
				{
					this.OnIDPAISChanging(value);
					this.SendPropertyChanging();
					this._IDPAIS = value;
					this.SendPropertyChanged("IDPAIS");
					this.OnIDPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Genero")]
	public partial class Genero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDGENERO;
		
		private string _NOMBRE_GENERO;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDGENEROChanging(int value);
    partial void OnIDGENEROChanged();
    partial void OnNOMBRE_GENEROChanging(string value);
    partial void OnNOMBRE_GENEROChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Genero()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGENERO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDGENERO
		{
			get
			{
				return this._IDGENERO;
			}
			set
			{
				if ((this._IDGENERO != value))
				{
					this.OnIDGENEROChanging(value);
					this.SendPropertyChanging();
					this._IDGENERO = value;
					this.SendPropertyChanged("IDGENERO");
					this.OnIDGENEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_GENERO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_GENERO
		{
			get
			{
				return this._NOMBRE_GENERO;
			}
			set
			{
				if ((this._NOMBRE_GENERO != value))
				{
					this.OnNOMBRE_GENEROChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_GENERO = value;
					this.SendPropertyChanged("NOMBRE_GENERO");
					this.OnNOMBRE_GENEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sala")]
	public partial class Sala : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDSALA;
		
		private int _IDCINE;
		
		private int _CANT_BUTACAS;
		
		private int _CANT_FILAS;
		
		private System.Nullable<int> _CANT_COLUMNAS;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSALAChanging(int value);
    partial void OnIDSALAChanged();
    partial void OnIDCINEChanging(int value);
    partial void OnIDCINEChanged();
    partial void OnCANT_BUTACASChanging(int value);
    partial void OnCANT_BUTACASChanged();
    partial void OnCANT_FILASChanging(int value);
    partial void OnCANT_FILASChanged();
    partial void OnCANT_COLUMNASChanging(System.Nullable<int> value);
    partial void OnCANT_COLUMNASChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Sala()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSALA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDSALA
		{
			get
			{
				return this._IDSALA;
			}
			set
			{
				if ((this._IDSALA != value))
				{
					this.OnIDSALAChanging(value);
					this.SendPropertyChanging();
					this._IDSALA = value;
					this.SendPropertyChanged("IDSALA");
					this.OnIDSALAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCINE", DbType="Int NOT NULL")]
		public int IDCINE
		{
			get
			{
				return this._IDCINE;
			}
			set
			{
				if ((this._IDCINE != value))
				{
					this.OnIDCINEChanging(value);
					this.SendPropertyChanging();
					this._IDCINE = value;
					this.SendPropertyChanged("IDCINE");
					this.OnIDCINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANT_BUTACAS", DbType="Int NOT NULL")]
		public int CANT_BUTACAS
		{
			get
			{
				return this._CANT_BUTACAS;
			}
			set
			{
				if ((this._CANT_BUTACAS != value))
				{
					this.OnCANT_BUTACASChanging(value);
					this.SendPropertyChanging();
					this._CANT_BUTACAS = value;
					this.SendPropertyChanged("CANT_BUTACAS");
					this.OnCANT_BUTACASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANT_FILAS", DbType="Int NOT NULL")]
		public int CANT_FILAS
		{
			get
			{
				return this._CANT_FILAS;
			}
			set
			{
				if ((this._CANT_FILAS != value))
				{
					this.OnCANT_FILASChanging(value);
					this.SendPropertyChanging();
					this._CANT_FILAS = value;
					this.SendPropertyChanged("CANT_FILAS");
					this.OnCANT_FILASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANT_COLUMNAS", DbType="Int")]
		public System.Nullable<int> CANT_COLUMNAS
		{
			get
			{
				return this._CANT_COLUMNAS;
			}
			set
			{
				if ((this._CANT_COLUMNAS != value))
				{
					this.OnCANT_COLUMNASChanging(value);
					this.SendPropertyChanging();
					this._CANT_COLUMNAS = value;
					this.SendPropertyChanged("CANT_COLUMNAS");
					this.OnCANT_COLUMNASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Modalidad")]
	public partial class Tipo_Modalidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPO_MODALIDAD;
		
		private string _NOMBRE;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPO_MODALIDADChanging(int value);
    partial void OnIDTIPO_MODALIDADChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Tipo_Modalidad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO_MODALIDAD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDTIPO_MODALIDAD
		{
			get
			{
				return this._IDTIPO_MODALIDAD;
			}
			set
			{
				if ((this._IDTIPO_MODALIDAD != value))
				{
					this.OnIDTIPO_MODALIDADChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO_MODALIDAD = value;
					this.SendPropertyChanged("IDTIPO_MODALIDAD");
					this.OnIDTIPO_MODALIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Empleado")]
	public partial class Tipo_Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPO_EMPLEADO;
		
		private string _NOMBRE;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPO_EMPLEADOChanging(int value);
    partial void OnIDTIPO_EMPLEADOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Tipo_Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO_EMPLEADO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDTIPO_EMPLEADO
		{
			get
			{
				return this._IDTIPO_EMPLEADO;
			}
			set
			{
				if ((this._IDTIPO_EMPLEADO != value))
				{
					this.OnIDTIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO_EMPLEADO = value;
					this.SendPropertyChanged("IDTIPO_EMPLEADO");
					this.OnIDTIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEMPLEADO;
		
		private string _NOMBRE_EMPLEADO;
		
		private string _APELLIDO;
		
		private decimal _SUELDO;
		
		private string _FECHA_INICIO;
		
		private int _IDTIPO_MODALIDAD;
		
		private int _IDTIPO_EMPLEADO;
		
		private string _USUARIO;
		
		private string _CONTRASEÑA;
		
		private bool _HABILITADO;
		
		private bool _BLOQUEADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEMPLEADOChanging(int value);
    partial void OnIDEMPLEADOChanged();
    partial void OnNOMBRE_EMPLEADOChanging(string value);
    partial void OnNOMBRE_EMPLEADOChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnSUELDOChanging(decimal value);
    partial void OnSUELDOChanged();
    partial void OnFECHA_INICIOChanging(string value);
    partial void OnFECHA_INICIOChanged();
    partial void OnIDTIPO_MODALIDADChanging(int value);
    partial void OnIDTIPO_MODALIDADChanged();
    partial void OnIDTIPO_EMPLEADOChanging(int value);
    partial void OnIDTIPO_EMPLEADOChanged();
    partial void OnUSUARIOChanging(string value);
    partial void OnUSUARIOChanged();
    partial void OnCONTRASEÑAChanging(string value);
    partial void OnCONTRASEÑAChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    partial void OnBLOQUEADOChanging(bool value);
    partial void OnBLOQUEADOChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPLEADO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDEMPLEADO
		{
			get
			{
				return this._IDEMPLEADO;
			}
			set
			{
				if ((this._IDEMPLEADO != value))
				{
					this.OnIDEMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._IDEMPLEADO = value;
					this.SendPropertyChanged("IDEMPLEADO");
					this.OnIDEMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMPLEADO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_EMPLEADO
		{
			get
			{
				return this._NOMBRE_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_EMPLEADO != value))
				{
					this.OnNOMBRE_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_EMPLEADO = value;
					this.SendPropertyChanged("NOMBRE_EMPLEADO");
					this.OnNOMBRE_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this.OnAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO = value;
					this.SendPropertyChanged("APELLIDO");
					this.OnAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUELDO", DbType="Money NOT NULL")]
		public decimal SUELDO
		{
			get
			{
				return this._SUELDO;
			}
			set
			{
				if ((this._SUELDO != value))
				{
					this.OnSUELDOChanging(value);
					this.SendPropertyChanging();
					this._SUELDO = value;
					this.SendPropertyChanged("SUELDO");
					this.OnSUELDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="NVarChar(50)")]
		public string FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO_MODALIDAD", DbType="Int NOT NULL")]
		public int IDTIPO_MODALIDAD
		{
			get
			{
				return this._IDTIPO_MODALIDAD;
			}
			set
			{
				if ((this._IDTIPO_MODALIDAD != value))
				{
					this.OnIDTIPO_MODALIDADChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO_MODALIDAD = value;
					this.SendPropertyChanged("IDTIPO_MODALIDAD");
					this.OnIDTIPO_MODALIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO_EMPLEADO", DbType="Int NOT NULL")]
		public int IDTIPO_EMPLEADO
		{
			get
			{
				return this._IDTIPO_EMPLEADO;
			}
			set
			{
				if ((this._IDTIPO_EMPLEADO != value))
				{
					this.OnIDTIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO_EMPLEADO = value;
					this.SendPropertyChanged("IDTIPO_EMPLEADO");
					this.OnIDTIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this.OnUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._USUARIO = value;
					this.SendPropertyChanged("USUARIO");
					this.OnUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASEÑA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTRASEÑA
		{
			get
			{
				return this._CONTRASEÑA;
			}
			set
			{
				if ((this._CONTRASEÑA != value))
				{
					this.OnCONTRASEÑAChanging(value);
					this.SendPropertyChanging();
					this._CONTRASEÑA = value;
					this.SendPropertyChanged("CONTRASEÑA");
					this.OnCONTRASEÑAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOQUEADO", DbType="Bit NOT NULL")]
		public bool BLOQUEADO
		{
			get
			{
				return this._BLOQUEADO;
			}
			set
			{
				if ((this._BLOQUEADO != value))
				{
					this.OnBLOQUEADOChanging(value);
					this.SendPropertyChanging();
					this._BLOQUEADO = value;
					this.SendPropertyChanged("BLOQUEADO");
					this.OnBLOQUEADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcion")]
	public partial class Funcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFUNCION;
		
		private string _FECHAFUNCION;
		
		private int _IDPELICULA;
		
		private int _IDCINE;
		
		private int _IDSALA;
		
		private string _HORARIO;
		
		private System.Nullable<bool> _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFUNCIONChanging(int value);
    partial void OnIDFUNCIONChanged();
    partial void OnFECHAFUNCIONChanging(string value);
    partial void OnFECHAFUNCIONChanged();
    partial void OnIDPELICULAChanging(int value);
    partial void OnIDPELICULAChanged();
    partial void OnIDCINEChanging(int value);
    partial void OnIDCINEChanged();
    partial void OnIDSALAChanging(int value);
    partial void OnIDSALAChanged();
    partial void OnHORARIOChanging(string value);
    partial void OnHORARIOChanged();
    partial void OnHABILITADOChanging(System.Nullable<bool> value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Funcion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFUNCION", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFUNCION
		{
			get
			{
				return this._IDFUNCION;
			}
			set
			{
				if ((this._IDFUNCION != value))
				{
					this.OnIDFUNCIONChanging(value);
					this.SendPropertyChanging();
					this._IDFUNCION = value;
					this.SendPropertyChanged("IDFUNCION");
					this.OnIDFUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAFUNCION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FECHAFUNCION
		{
			get
			{
				return this._FECHAFUNCION;
			}
			set
			{
				if ((this._FECHAFUNCION != value))
				{
					this.OnFECHAFUNCIONChanging(value);
					this.SendPropertyChanging();
					this._FECHAFUNCION = value;
					this.SendPropertyChanged("FECHAFUNCION");
					this.OnFECHAFUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPELICULA", DbType="Int NOT NULL")]
		public int IDPELICULA
		{
			get
			{
				return this._IDPELICULA;
			}
			set
			{
				if ((this._IDPELICULA != value))
				{
					this.OnIDPELICULAChanging(value);
					this.SendPropertyChanging();
					this._IDPELICULA = value;
					this.SendPropertyChanged("IDPELICULA");
					this.OnIDPELICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCINE", DbType="Int NOT NULL")]
		public int IDCINE
		{
			get
			{
				return this._IDCINE;
			}
			set
			{
				if ((this._IDCINE != value))
				{
					this.OnIDCINEChanging(value);
					this.SendPropertyChanging();
					this._IDCINE = value;
					this.SendPropertyChanged("IDCINE");
					this.OnIDCINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSALA", DbType="Int NOT NULL")]
		public int IDSALA
		{
			get
			{
				return this._IDSALA;
			}
			set
			{
				if ((this._IDSALA != value))
				{
					this.OnIDSALAChanging(value);
					this.SendPropertyChanging();
					this._IDSALA = value;
					this.SendPropertyChanged("IDSALA");
					this.OnIDSALAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORARIO", DbType="NVarChar(50)")]
		public string HORARIO
		{
			get
			{
				return this._HORARIO;
			}
			set
			{
				if ((this._HORARIO != value))
				{
					this.OnHORARIOChanging(value);
					this.SendPropertyChanging();
					this._HORARIO = value;
					this.SendPropertyChanged("HORARIO");
					this.OnHORARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit")]
		public System.Nullable<bool> HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Entrada")]
	public partial class Tipo_Entrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPOENTRADA;
		
		private string _NOMBRE;
		
		private System.Nullable<bool> _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPOENTRADAChanging(int value);
    partial void OnIDTIPOENTRADAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnHABILITADOChanging(System.Nullable<bool> value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Tipo_Entrada()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOENTRADA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDTIPOENTRADA
		{
			get
			{
				return this._IDTIPOENTRADA;
			}
			set
			{
				if ((this._IDTIPOENTRADA != value))
				{
					this.OnIDTIPOENTRADAChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOENTRADA = value;
					this.SendPropertyChanged("IDTIPOENTRADA");
					this.OnIDTIPOENTRADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit")]
		public System.Nullable<bool> HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Butaca")]
	public partial class Butaca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFUNCION;
		
		private int _IDBUTACA;
		
		private int _INDICE_FILA;
		
		private int _INDICE_COLUMNA;
		
		private bool _LIBRE;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFUNCIONChanging(int value);
    partial void OnIDFUNCIONChanged();
    partial void OnIDBUTACAChanging(int value);
    partial void OnIDBUTACAChanged();
    partial void OnINDICE_FILAChanging(int value);
    partial void OnINDICE_FILAChanged();
    partial void OnINDICE_COLUMNAChanging(int value);
    partial void OnINDICE_COLUMNAChanged();
    partial void OnLIBREChanging(bool value);
    partial void OnLIBREChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Butaca()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFUNCION", DbType="Int NOT NULL")]
		public int IDFUNCION
		{
			get
			{
				return this._IDFUNCION;
			}
			set
			{
				if ((this._IDFUNCION != value))
				{
					this.OnIDFUNCIONChanging(value);
					this.SendPropertyChanging();
					this._IDFUNCION = value;
					this.SendPropertyChanged("IDFUNCION");
					this.OnIDFUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBUTACA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBUTACA
		{
			get
			{
				return this._IDBUTACA;
			}
			set
			{
				if ((this._IDBUTACA != value))
				{
					this.OnIDBUTACAChanging(value);
					this.SendPropertyChanging();
					this._IDBUTACA = value;
					this.SendPropertyChanged("IDBUTACA");
					this.OnIDBUTACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDICE_FILA", DbType="Int NOT NULL")]
		public int INDICE_FILA
		{
			get
			{
				return this._INDICE_FILA;
			}
			set
			{
				if ((this._INDICE_FILA != value))
				{
					this.OnINDICE_FILAChanging(value);
					this.SendPropertyChanging();
					this._INDICE_FILA = value;
					this.SendPropertyChanged("INDICE_FILA");
					this.OnINDICE_FILAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDICE_COLUMNA", DbType="Int NOT NULL")]
		public int INDICE_COLUMNA
		{
			get
			{
				return this._INDICE_COLUMNA;
			}
			set
			{
				if ((this._INDICE_COLUMNA != value))
				{
					this.OnINDICE_COLUMNAChanging(value);
					this.SendPropertyChanging();
					this._INDICE_COLUMNA = value;
					this.SendPropertyChanged("INDICE_COLUMNA");
					this.OnINDICE_COLUMNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIBRE", DbType="Bit NOT NULL")]
		public bool LIBRE
		{
			get
			{
				return this._LIBRE;
			}
			set
			{
				if ((this._LIBRE != value))
				{
					this.OnLIBREChanging(value);
					this.SendPropertyChanging();
					this._LIBRE = value;
					this.SendPropertyChanged("LIBRE");
					this.OnLIBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcion_Entrada")]
	public partial class Funcion_Entrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFUNCION;
		
		private int _IDTIPOENTRADA;
		
		private System.Nullable<decimal> _PRECIO;
		
		private System.Nullable<bool> _HABILITADO;
		
		private int _IDENTRADA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFUNCIONChanging(int value);
    partial void OnIDFUNCIONChanged();
    partial void OnIDTIPOENTRADAChanging(int value);
    partial void OnIDTIPOENTRADAChanged();
    partial void OnPRECIOChanging(System.Nullable<decimal> value);
    partial void OnPRECIOChanged();
    partial void OnHABILITADOChanging(System.Nullable<bool> value);
    partial void OnHABILITADOChanged();
    partial void OnIDENTRADAChanging(int value);
    partial void OnIDENTRADAChanged();
    #endregion
		
		public Funcion_Entrada()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFUNCION", DbType="Int NOT NULL")]
		public int IDFUNCION
		{
			get
			{
				return this._IDFUNCION;
			}
			set
			{
				if ((this._IDFUNCION != value))
				{
					this.OnIDFUNCIONChanging(value);
					this.SendPropertyChanging();
					this._IDFUNCION = value;
					this.SendPropertyChanged("IDFUNCION");
					this.OnIDFUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOENTRADA", DbType="Int NOT NULL")]
		public int IDTIPOENTRADA
		{
			get
			{
				return this._IDTIPOENTRADA;
			}
			set
			{
				if ((this._IDTIPOENTRADA != value))
				{
					this.OnIDTIPOENTRADAChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOENTRADA = value;
					this.SendPropertyChanged("IDTIPOENTRADA");
					this.OnIDTIPOENTRADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit")]
		public System.Nullable<bool> HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTRADA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDENTRADA
		{
			get
			{
				return this._IDENTRADA;
			}
			set
			{
				if ((this._IDENTRADA != value))
				{
					this.OnIDENTRADAChanging(value);
					this.SendPropertyChanging();
					this._IDENTRADA = value;
					this.SendPropertyChanged("IDENTRADA");
					this.OnIDENTRADAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reserva")]
	public partial class Reserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRESERVA;
		
		private System.Nullable<int> _IDCLIENTE;
		
		private System.Nullable<int> _IDEMPLEADO;
		
		private System.Nullable<decimal> _TOTAL;
		
		private bool _HABILITADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRESERVAChanging(int value);
    partial void OnIDRESERVAChanged();
    partial void OnIDCLIENTEChanging(System.Nullable<int> value);
    partial void OnIDCLIENTEChanged();
    partial void OnIDEMPLEADOChanging(System.Nullable<int> value);
    partial void OnIDEMPLEADOChanged();
    partial void OnTOTALChanging(System.Nullable<decimal> value);
    partial void OnTOTALChanged();
    partial void OnHABILITADOChanging(bool value);
    partial void OnHABILITADOChanged();
    #endregion
		
		public Reserva()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRESERVA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDRESERVA
		{
			get
			{
				return this._IDRESERVA;
			}
			set
			{
				if ((this._IDRESERVA != value))
				{
					this.OnIDRESERVAChanging(value);
					this.SendPropertyChanging();
					this._IDRESERVA = value;
					this.SendPropertyChanged("IDRESERVA");
					this.OnIDRESERVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="Int")]
		public System.Nullable<int> IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this.OnIDCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDCLIENTE = value;
					this.SendPropertyChanged("IDCLIENTE");
					this.OnIDCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPLEADO", DbType="Int")]
		public System.Nullable<int> IDEMPLEADO
		{
			get
			{
				return this._IDEMPLEADO;
			}
			set
			{
				if ((this._IDEMPLEADO != value))
				{
					this.OnIDEMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._IDEMPLEADO = value;
					this.SendPropertyChanged("IDEMPLEADO");
					this.OnIDEMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Bit NOT NULL")]
		public bool HABILITADO
		{
			get
			{
				return this._HABILITADO;
			}
			set
			{
				if ((this._HABILITADO != value))
				{
					this.OnHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._HABILITADO = value;
					this.SendPropertyChanged("HABILITADO");
					this.OnHABILITADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Reserva")]
	public partial class Detalle_Reserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRESERVA;
		
		private int _IDCLIENTE;
		
		private System.Nullable<int> _PRECIO;
		
		private System.Nullable<int> _IDFUNCION;
		
		private int _IDBUTACA;
		
		private bool _HABILTIADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRESERVAChanging(int value);
    partial void OnIDRESERVAChanged();
    partial void OnIDCLIENTEChanging(int value);
    partial void OnIDCLIENTEChanged();
    partial void OnPRECIOChanging(System.Nullable<int> value);
    partial void OnPRECIOChanged();
    partial void OnIDFUNCIONChanging(System.Nullable<int> value);
    partial void OnIDFUNCIONChanged();
    partial void OnIDBUTACAChanging(int value);
    partial void OnIDBUTACAChanged();
    partial void OnHABILTIADOChanging(bool value);
    partial void OnHABILTIADOChanged();
    #endregion
		
		public Detalle_Reserva()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRESERVA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDRESERVA
		{
			get
			{
				return this._IDRESERVA;
			}
			set
			{
				if ((this._IDRESERVA != value))
				{
					this.OnIDRESERVAChanging(value);
					this.SendPropertyChanging();
					this._IDRESERVA = value;
					this.SendPropertyChanged("IDRESERVA");
					this.OnIDRESERVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="Int NOT NULL")]
		public int IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this.OnIDCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDCLIENTE = value;
					this.SendPropertyChanged("IDCLIENTE");
					this.OnIDCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int")]
		public System.Nullable<int> PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFUNCION", DbType="Int")]
		public System.Nullable<int> IDFUNCION
		{
			get
			{
				return this._IDFUNCION;
			}
			set
			{
				if ((this._IDFUNCION != value))
				{
					this.OnIDFUNCIONChanging(value);
					this.SendPropertyChanging();
					this._IDFUNCION = value;
					this.SendPropertyChanged("IDFUNCION");
					this.OnIDFUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBUTACA", DbType="Int NOT NULL")]
		public int IDBUTACA
		{
			get
			{
				return this._IDBUTACA;
			}
			set
			{
				if ((this._IDBUTACA != value))
				{
					this.OnIDBUTACAChanging(value);
					this.SendPropertyChanging();
					this._IDBUTACA = value;
					this.SendPropertyChanged("IDBUTACA");
					this.OnIDBUTACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILTIADO", DbType="Bit NOT NULL")]
		public bool HABILTIADO
		{
			get
			{
				return this._HABILTIADO;
			}
			set
			{
				if ((this._HABILTIADO != value))
				{
					this.OnHABILTIADOChanging(value);
					this.SendPropertyChanging();
					this._HABILTIADO = value;
					this.SendPropertyChanged("HABILTIADO");
					this.OnHABILTIADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
